export const POKEMON_LIST_REQUEST = 'POKEMON_LIST_REQUEST';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL';

export const POKEMON_DETAILS_REQUEST = 'POKEMON_DETAILS_REQUEST';
export const POKEMON_DETAILS_SUCCESS = 'POKEMON_DETAILS_SUCCESS';
export const POKEMON_DETAILS_FAIL = 'POKEMON_DETAILS_FAIL';

export const POKEMON_CREATE_REQUEST = 'POKEMON_CREATE_REQUEST';
export const POKEMON_CREATE_SUCCESS = 'POKEMON_CREATE_SUCCESS';
export const POKEMON_CREATE_FAIL = 'POKEMON_CREATE_FAIL';
export const POKEMON_CREATE_RESET = 'POKEMON_CREATE_RESET';
